#!/bin/bash

if [ "${SCRIPT_DEBUG}" = "true" ] ; then
    set -x
    echo "Script debugging is enabled, allowing bash commands and their arguments to be printed as they are executed"
fi

# . $(dirname $0)/common.sh
source /usr/local/s2i/common.sh
source /usr/local/s2i/scl-enable-maven

LOCAL_SOURCE_DIR=/tmp/src

# Resulting WAR files will be deployed to /opt/eap/standalone/deployments
DEPLOY_DIR=$JBOSS_HOME/standalone/deployments

# JBoss AS data dir. Can be overridden.
DATA_DIR=${DATA_DIR:-$JBOSS_HOME/standalone/data}

# App data dir. Can be overridden.
APP_DATADIR=${APP_DATADIR:-data}

# -----------------------------------------------------------------------------
# ビルドした複数のwarファイルの出力先を設定する。
# ここで指定したディレクトリ配下のwarファイルがdeploymentsディレクトリにコピーされる。
# -----------------------------------------------------------------------------
ARTIFACT_DIR=${FESENV_RUNTIME_NAME}-pc/target,${FESENV_RUNTIME_NAME}-mbl/target,${FESENV_RUNTIME_NAME}-sp/target
# -----------------------------------------------------------------------------
# 追加ここまで
# -----------------------------------------------------------------------------

# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
# artifacts (*.war, *.jar)
ARTIFACT_DIR=${ARTIFACT_DIR:-target}

if [ -f $LOCAL_SOURCE_DIR/configuration/settings.xml ]; then
  echo "Copying maven config file from project..."
  mkdir -p $HOME/.m2
  mv $LOCAL_SOURCE_DIR/configuration/settings.xml $HOME/.m2
fi


configure_proxy
configure_mirrors

manage_incremental_build

# If a pom.xml is present, this is a normal build scenario
# so run maven.
if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
  pushd $LOCAL_SOURCE_DIR &> /dev/null

  # Add JVM default options
  export MAVEN_OPTS="${MAVEN_OPTS:-$(/opt/run-java/java-default-options)}"
  MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package}

  # Use maven batch mode (CLOUD-579)
  # Always force IPv4 (CLOUD-188)
  # Append user-supplied arguments (CLOUD-412)
  MAVEN_ARGS="$MAVEN_ARGS --batch-mode -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"

  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
  echo "Using MAVEN_OPTS '${MAVEN_OPTS}'"

  echo "Using $(mvn --version)"

  # Execute the actual build
  # -----------------------------------------------------------------------------
  # 不要なビルドの実行を避けるため、pushコマンドを使用して
  # ビルド対象の各チャネルのディレクトリへ移動する。
  # また、ディレクトリが存在しない場合はスキップする。
  # -----------------------------------------------------------------------------
  for channel in pc mbl sp; do
    if [ -d $LOCAL_SOURCE_DIR/${FESENV_RUNTIME_NAME}-${channel} ]; then
      pushd $LOCAL_SOURCE_DIR/${FESENV_RUNTIME_NAME}-${channel} &> /dev/null
      mvn $MAVEN_ARGS
      ERR=$?
        if [ $ERR -ne 0 ]; then
          echo "Aborting due to error code $ERR from Maven build"
          exit $ERR
        fi
      popd &> /dev/null
    fi
  done

  # -----------------------------------------------------------------------------
  # 追加ここまで
  # -----------------------------------------------------------------------------

  # Expand each ARTIFACT_DIR entry to absolute path by prefixing it with $LOCAL_SOURCE_DIR
  IFS=',' read -a artifact_dir_entries <<< "$ARTIFACT_DIR"
  artifact_dir_entries=($(printf "$LOCAL_SOURCE_DIR/%s\n" "${artifact_dir_entries[@]}" | tr '\n' ','))

  # Copy built artifacts (if any!) from the target/ directory
  # (or $ARTIFACT_DIR if specified) to the
  # $JBOSS_HOME/standalone/deployments/ directory for later deployment
  # Use artifact directories in absolute path form when copying artifacts
  copy_artifacts "${artifact_dir_entries[@]}" war ear rar jar

  # optionally clear the local maven repository after the build
  clear_maven_repository

  popd &> /dev/null
else
  copy_artifacts "$LOCAL_SOURCE_DIR" war ear rar jar
fi

# copy app data, if specified
if [ -n "$APP_DATADIR" ] && [ -d "$LOCAL_SOURCE_DIR/$APP_DATADIR" ]; then
  echo "Copying app data from ${APP_DATADIR} to ${DATA_DIR}..."
  rsync -rl --out-format='%n' "$LOCAL_SOURCE_DIR/$APP_DATADIR/" "$DATA_DIR"
  chmod -R g+rwX $DATA_DIR
fi

# Copy (probably binary) artifacts from the deployments/
# directory to the $JBOSS_HOME/standalone/deployments/
# directory for later deployment
copy_artifacts "$LOCAL_SOURCE_DIR/deployments" war ear rar jar

if [ -d $LOCAL_SOURCE_DIR/configuration ]; then
  file_count=$(ls -1 $LOCAL_SOURCE_DIR/configuration | wc -l)
  if [ $file_count -gt 0 ]; then
    echo "Copying config files from project..."
    cp -v $LOCAL_SOURCE_DIR/configuration/* $JBOSS_HOME/standalone/configuration/
  fi
fi

if [ -d $LOCAL_SOURCE_DIR/modules ]; then
  echo "Copying modules from project..."
  cp -vr $LOCAL_SOURCE_DIR/modules/* $JBOSS_HOME/modules/
fi

# -----------------------------------------------------------------------------
# Red Hat Added
# -----------------------------------------------------------------------------
mkdir -p /tmp/build
curl ${OPENSHIFT_BUILD_SOURCE/.git//}archive/master.zip -o /tmp/build/master.zip -L
unzip -d /tmp/build /tmp/build/master.zip 

REPOSITORY_NAME=${OPENSHIFT_BUILD_SOURCE##h*/}

echo "Copying config files from project..."
cp -v /tmp/build/${REPOSITORY_NAME%%.*}-master/App/s2i_commons/pl/configuration/* $JBOSS_HOME/standalone/configuration/

echo "Copying modules from project..."
cp -vr /tmp/build/${REPOSITORY_NAME%%.*}-master/App/s2i_commons/pl/modules/* $JBOSS_HOME/modules/

echo "Copying batch files from project..."
mkdir -p /home/jboss/batch
cp -vr /tmp/build/${REPOSITORY_NAME%%.*}-master/App/s2i_commons/pl/batch/* /home/jboss/batch

echo "Copying dtd files from project..."
mkdir -p /home/jboss/dtds
cp -vr /tmp/build/${REPOSITORY_NAME%%.*}-master/App/s2i_commons/pl/dtds/* /home/jboss/dtds
# -----------------------------------------------------------------------------
# Red Hat Added
# -----------------------------------------------------------------------------

function copy_injected {
  source_dir=$1
  target_dir=$2

  if [ -d "$source_dir" ]; then
    cp -rf ${source_dir}/* $target_dir
  fi
}

if [ -n $CUSTOM_INSTALL_DIRECTORIES ]; then
  IFS=',' read -a install_dir_entries <<< $CUSTOM_INSTALL_DIRECTORIES
  for install_dir_entry in "${install_dir_entries[@]}"; do
    for install_dir in $(find ${LOCAL_SOURCE_DIR}/$install_dir_entry -maxdepth 0 2>/dev/null); do
      chmod -R 755 ${install_dir}
      if [ -f ${install_dir}/install.sh ]; then
        ${install_dir}/install.sh ${install_dir}
      else
        copy_injected ${install_dir}/modules $JBOSS_HOME/modules

        copy_injected ${install_dir}/configuration $JBOSS_HOME/standalone/configuration

        copy_artifacts ${install_dir}/deployments war ear rar jar
      fi
    done
  done
fi

# -----------------------------------------------------------------------------
# OpenShiftではデプロイファイル名＝ランタイム名となるため、
# デプロイするwarファイル名を、[アプリ名]-bl-[チャネル]-[バージョン番号].war から、
# バージョン番号を取り除く
# -----------------------------------------------------------------------------
for filepath in $(find ${install_dir}/deployments/ -type f -name "*.war"); do
  filename=`basename $filepath .war`
  channel=`echo ${filename} | cut -d '-' -f 3`
  mv -v ${install_dir}/deployments/${FESENV_RUNTIME_NAME}-${channel}-*.war ${install_dir}/deployments/${channel}.war
done

# -----------------------------------------------------------------------------
# spチャネルのwarファイルが存在する場合はそのwarファイルをコピーし
# sappチャネルのwarファイルを作成する
# -----------------------------------------------------------------------------
if [ -f ${install_dir}/deployments/sp.war ]; then
  cp -v ${install_dir}/deployments/sp.war ${install_dir}/deployments/sapp.war
fi

#-----------------------------------------------------------------------------
# 各チャネルのwarファイルにバッチ用のjboss-service.xmlファイルを差し込む
# -----------------------------------------------------------------------------
cd ${install_dir}/deployments/
mkdir META-INF
if [ -f ${install_dir}/deployments/pc.war ]; then
  cp /home/jboss/batch/jboss/pc/jboss-service.xml ./META-INF/
  jar uvf pc.war ./META-INF/jboss-service.xml
fi
if [ -f ${install_dir}/deployments/mbl.war ]; then
  cp /home/jboss/batch/jboss/mbl/jboss-service.xml ./META-INF/
  jar uvf mbl.war ./META-INF/jboss-service.xml
fi
if [ -f ${install_dir}/deployments/sp.war ]; then
  cp /home/jboss/batch/jboss/sp/jboss-service.xml ./META-INF/
  jar uvf sp.war ./META-INF/jboss-service.xml
fi
if [ -f ${install_dir}/deployments/sapp.war ]; then
  cp /home/jboss/batch/jboss/sapp/jboss-service.xml ./META-INF/
  jar uvf sapp.war ./META-INF/jboss-service.xml
fi
rm -r META-INF

# -----------------------------------------------------------------------------
# テキストファイルや画像ファイル、プロパティなど一部のリソースをアプリケーションから読み込むため
# warファイルから展開を行う
# チャネル毎に展開先を分けるためwarファイル名からチャネルの判定を行っている。
# warファイル名は[チャネル].warとなっている事が前提であるため注意する事
# -----------------------------------------------------------------------------
for filepath in $(find ${install_dir}/deployments/ -type f -name "*.war"); do
  channel=`basename $filepath .war`
  unzip -o ${install_dir}/deployments/${channel}.war -d ${HOME}/${channel} "WEB-INF/classes/*" || true
done

# -----------------------------------------------------------------------------
# 追加ここまで
# -----------------------------------------------------------------------------

chmod -R g+rwX $HOME

# Remove java tmp perf data dir owned by 185
rm -rf /tmp/hsperfdata_jboss

# -----------------------------------------------------------------------------
# Red Hat Added
# -----------------------------------------------------------------------------
rm -rf /tmp/build
# -----------------------------------------------------------------------------
# Red Hat Added
# -----------------------------------------------------------------------------

exit 0
